// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: smq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_smq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{0}
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_smq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{1}
}

type GetLatestOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestOffsetRequest) Reset() {
	*x = GetLatestOffsetRequest{}
	mi := &file_smq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestOffsetRequest) ProtoMessage() {}

func (x *GetLatestOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestOffsetRequest.ProtoReflect.Descriptor instead.
func (*GetLatestOffsetRequest) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{2}
}

func (x *GetLatestOffsetRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GetLatestOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestOffsetResponse) Reset() {
	*x = GetLatestOffsetResponse{}
	mi := &file_smq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestOffsetResponse) ProtoMessage() {}

func (x *GetLatestOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetLatestOffsetResponse) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestOffsetResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetEarliestOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEarliestOffsetRequest) Reset() {
	*x = GetEarliestOffsetRequest{}
	mi := &file_smq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEarliestOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEarliestOffsetRequest) ProtoMessage() {}

func (x *GetEarliestOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEarliestOffsetRequest.ProtoReflect.Descriptor instead.
func (*GetEarliestOffsetRequest) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{4}
}

func (x *GetEarliestOffsetRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GetEarliestOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEarliestOffsetResponse) Reset() {
	*x = GetEarliestOffsetResponse{}
	mi := &file_smq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEarliestOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEarliestOffsetResponse) ProtoMessage() {}

func (x *GetEarliestOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEarliestOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetEarliestOffsetResponse) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{5}
}

func (x *GetEarliestOffsetResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_smq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_smq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{7}
}

type ProduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_smq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{8}
}

func (x *ProduceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_smq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{9}
}

func (x *ProduceResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_smq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{10}
}

func (x *ConsumeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_smq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{11}
}

func (x *ConsumeResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ConsumeResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DeleteUntilOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUntilOffsetRequest) Reset() {
	*x = DeleteUntilOffsetRequest{}
	mi := &file_smq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUntilOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUntilOffsetRequest) ProtoMessage() {}

func (x *DeleteUntilOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUntilOffsetRequest.ProtoReflect.Descriptor instead.
func (*DeleteUntilOffsetRequest) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUntilOffsetRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DeleteUntilOffsetRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DeleteUntilOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUntilOffsetResponse) Reset() {
	*x = DeleteUntilOffsetResponse{}
	mi := &file_smq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUntilOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUntilOffsetResponse) ProtoMessage() {}

func (x *DeleteUntilOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUntilOffsetResponse.ProtoReflect.Descriptor instead.
func (*DeleteUntilOffsetResponse) Descriptor() ([]byte, []int) {
	return file_smq_proto_rawDescGZIP(), []int{13}
}

var File_smq_proto protoreflect.FileDescriptor

const file_smq_proto_rawDesc = "" +
	"\n" +
	"\tsmq.proto\x12\x03smq\"\x10\n" +
	"\x0eConnectRequest\"\x11\n" +
	"\x0fConnectResponse\".\n" +
	"\x16GetLatestOffsetRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"1\n" +
	"\x17GetLatestOffsetResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\"0\n" +
	"\x18GetEarliestOffsetRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"3\n" +
	"\x19GetEarliestOffsetResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\"*\n" +
	"\x12CreateTopicRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"\x15\n" +
	"\x13CreateTopicResponse\"@\n" +
	"\x0eProduceRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\")\n" +
	"\x0fProduceResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\">\n" +
	"\x0eConsumeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"C\n" +
	"\x0fConsumeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"H\n" +
	"\x18DeleteUntilOffsetRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\x1b\n" +
	"\x19DeleteUntilOffsetResponse2\xfc\x04\n" +
	"\x12SuhaibMessageQueue\x126\n" +
	"\aConnect\x12\x13.smq.ConnectRequest\x1a\x14.smq.ConnectResponse\"\x00\x12N\n" +
	"\x0fGetLatestOffset\x12\x1b.smq.GetLatestOffsetRequest\x1a\x1c.smq.GetLatestOffsetResponse\"\x00\x12T\n" +
	"\x11GetEarliestOffset\x12\x1d.smq.GetEarliestOffsetRequest\x1a\x1e.smq.GetEarliestOffsetResponse\"\x00\x12B\n" +
	"\vCreateTopic\x12\x17.smq.CreateTopicRequest\x1a\x18.smq.CreateTopicResponse\"\x00\x126\n" +
	"\aProduce\x12\x13.smq.ProduceRequest\x1a\x14.smq.ProduceResponse\"\x00\x126\n" +
	"\aConsume\x12\x13.smq.ConsumeRequest\x1a\x14.smq.ConsumeResponse\"\x00\x12>\n" +
	"\rStreamProduce\x12\x13.smq.ProduceRequest\x1a\x14.smq.ProduceResponse\"\x00(\x01\x12>\n" +
	"\rStreamConsume\x12\x13.smq.ConsumeRequest\x1a\x14.smq.ConsumeResponse\"\x000\x01\x12T\n" +
	"\x11DeleteUntilOffset\x12\x1d.smq.DeleteUntilOffsetRequest\x1a\x1e.smq.DeleteUntilOffsetResponse\"\x00B\tZ\a./protob\x06proto3"

var (
	file_smq_proto_rawDescOnce sync.Once
	file_smq_proto_rawDescData []byte
)

func file_smq_proto_rawDescGZIP() []byte {
	file_smq_proto_rawDescOnce.Do(func() {
		file_smq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smq_proto_rawDesc), len(file_smq_proto_rawDesc)))
	})
	return file_smq_proto_rawDescData
}

var file_smq_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_smq_proto_goTypes = []any{
	(*ConnectRequest)(nil),            // 0: smq.ConnectRequest
	(*ConnectResponse)(nil),           // 1: smq.ConnectResponse
	(*GetLatestOffsetRequest)(nil),    // 2: smq.GetLatestOffsetRequest
	(*GetLatestOffsetResponse)(nil),   // 3: smq.GetLatestOffsetResponse
	(*GetEarliestOffsetRequest)(nil),  // 4: smq.GetEarliestOffsetRequest
	(*GetEarliestOffsetResponse)(nil), // 5: smq.GetEarliestOffsetResponse
	(*CreateTopicRequest)(nil),        // 6: smq.CreateTopicRequest
	(*CreateTopicResponse)(nil),       // 7: smq.CreateTopicResponse
	(*ProduceRequest)(nil),            // 8: smq.ProduceRequest
	(*ProduceResponse)(nil),           // 9: smq.ProduceResponse
	(*ConsumeRequest)(nil),            // 10: smq.ConsumeRequest
	(*ConsumeResponse)(nil),           // 11: smq.ConsumeResponse
	(*DeleteUntilOffsetRequest)(nil),  // 12: smq.DeleteUntilOffsetRequest
	(*DeleteUntilOffsetResponse)(nil), // 13: smq.DeleteUntilOffsetResponse
}
var file_smq_proto_depIdxs = []int32{
	0,  // 0: smq.SuhaibMessageQueue.Connect:input_type -> smq.ConnectRequest
	2,  // 1: smq.SuhaibMessageQueue.GetLatestOffset:input_type -> smq.GetLatestOffsetRequest
	4,  // 2: smq.SuhaibMessageQueue.GetEarliestOffset:input_type -> smq.GetEarliestOffsetRequest
	6,  // 3: smq.SuhaibMessageQueue.CreateTopic:input_type -> smq.CreateTopicRequest
	8,  // 4: smq.SuhaibMessageQueue.Produce:input_type -> smq.ProduceRequest
	10, // 5: smq.SuhaibMessageQueue.Consume:input_type -> smq.ConsumeRequest
	8,  // 6: smq.SuhaibMessageQueue.StreamProduce:input_type -> smq.ProduceRequest
	10, // 7: smq.SuhaibMessageQueue.StreamConsume:input_type -> smq.ConsumeRequest
	12, // 8: smq.SuhaibMessageQueue.DeleteUntilOffset:input_type -> smq.DeleteUntilOffsetRequest
	1,  // 9: smq.SuhaibMessageQueue.Connect:output_type -> smq.ConnectResponse
	3,  // 10: smq.SuhaibMessageQueue.GetLatestOffset:output_type -> smq.GetLatestOffsetResponse
	5,  // 11: smq.SuhaibMessageQueue.GetEarliestOffset:output_type -> smq.GetEarliestOffsetResponse
	7,  // 12: smq.SuhaibMessageQueue.CreateTopic:output_type -> smq.CreateTopicResponse
	9,  // 13: smq.SuhaibMessageQueue.Produce:output_type -> smq.ProduceResponse
	11, // 14: smq.SuhaibMessageQueue.Consume:output_type -> smq.ConsumeResponse
	9,  // 15: smq.SuhaibMessageQueue.StreamProduce:output_type -> smq.ProduceResponse
	11, // 16: smq.SuhaibMessageQueue.StreamConsume:output_type -> smq.ConsumeResponse
	13, // 17: smq.SuhaibMessageQueue.DeleteUntilOffset:output_type -> smq.DeleteUntilOffsetResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_smq_proto_init() }
func file_smq_proto_init() {
	if File_smq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smq_proto_rawDesc), len(file_smq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smq_proto_goTypes,
		DependencyIndexes: file_smq_proto_depIdxs,
		MessageInfos:      file_smq_proto_msgTypes,
	}.Build()
	File_smq_proto = out.File
	file_smq_proto_goTypes = nil
	file_smq_proto_depIdxs = nil
}
